### ISSUE TITLE
Stars get doubled when aligned in center

### ISSUE THREAD

**Issue by nimeshdhruve** [prrashi/rateYo#23]
First of all, great plugin. Thanks for sharing.

I have noticed that when the stars are created inside a large container and are center aligned then in some corner cases they get doubled. Mainly when you are hovering mouse on the last star's edges.

I have also tried to set the margin to auto and align stars in center instead of `center` block and still they were getting doubled.

Example:
![doublestar](https://cloud.githubusercontent.com/assets/7783989/23268631/5638839a-f9bc-11e6-9c39-f1f87c2b64f0.png)

This is what the HTML looks like:
![inspectelement](https://cloud.githubusercontent.com/assets/7783989/23268461/d2acbe10-f9bb-11e6-87dd-2733275910e2.png)

Below is the Java Script code:
```
$("#rate_instance").rateYo({
            spacing: "20px",
            starWidth: "40px",
            normalFill: "#A0A0A0", //The background color for the un-rated part of a star
            ratedFill: "#963378", //The color for the rated part of a star
            maxValue: 5, //The Maximum value, you want the rating to end with
            fullStar: true,
            onInit: function (rating, rateYoInstance) {
             
            },
            onChange: function (rating, rateYoInstance) {

            },
            onSet: function (rating, rateYoInstance) {

            }
        });
```

Browswer: Firefox 51.01 as well as Chrome 56.0.2924.87

**Comment by prrashi** [comment]
Hey!, looks interesting, Is it possible to share the code in jsfiddle ?

**Comment by nimeshdhruve** [comment]
Please find jsFiddle: https://jsfiddle.net/474a9p37/

I was able to reproduce in jsFiddle too. you just need to hover on the edges of the fifth star. It is hard to miss once you see it.

![jsfiddle](https://cloud.githubusercontent.com/assets/7783989/23273401/dc026a8a-f9cc-11e6-869b-3f66aba1e047.png)

**Comment by prrashi** [comment]
Hey @nimeshdhruve , Sorry for the delayed reply.

I think the issue is not with center alignment. I am able to get this only sometimes for the same browser. 

I think its calculation error described here - https://modernweb.com/what-every-javascript-developer-should-know-about-floating-points/

I am able to get the same kind of result by setting the width of `jq-ry-rated-group` to more than 100% , please see the attached pic
![screen shot 2017-04-05 at 11 05 49 pm](https://cloud.githubusercontent.com/assets/1190354/24718685/8bd53bfc-1a54-11e7-8586-c29c0b8c38b4.png)

I will put some gaurd conditions in `showRating` function of the source code, so that the width does not exceed 100% and below 0% . Please try with the conditions (attached pic of the code) and let me know if you still face it.

![screen shot 2017-04-05 at 11 09 03 pm](https://cloud.githubusercontent.com/assets/1190354/24718799/fdf107fc-1a54-11e7-9085-7b4f505ba25f.png)

**Comment by prrashi** [comment]
I think this is resolved
